# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ef92378c8cc7679d8b2750009f744fbe5eff4d3776fd1c5ca6d7166d0bbf9ee11b2081a3d924c2bf1fa09ba30d99b562970eb2a83c3bcee01ba2b36e5360261

test:
  secret_key_base: bbd99f437b97efb9383758197815769bedba85dd8ad16778620853b7763cb6f7617391477c451e8eb083ebe021ef77f491bc72c472806b9497ab5a855029461a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
